# CNB 云原生构建配置
main:
  push:
    - docker:
        image: node:20
      stages:
        - name: install
          script:
            - npm install
        - name: build
          script:
            - npm run build
        - name: deploy
          script:
            - echo "部署静态网站..."
      exports:
        pages:
          - path: dist

